### ISSUE TITLE
Downstream tests

### ISSUE THREAD

**Issue by bryevdv** [poldavezac/BokehServer.jl#5]
Hi, @poldavezac  first I just want to say that it was great to discover this. I have thought that Bokeh+Julia would make a great combination for many years. But I'm a casual Julia use at best, and something like this really needs to be undertaken by someone with more experience and a stronger point of view. So, thanks!

Having been pointed here, I just wanted to reach out and offer a few comments:

* Just as an FYI a new major release (3.0) is expected this Summer, there will be some breaking changes. Please let us know if there are any issues you run into that we can advise on.
* Apart from major releases, we'd like to minimize any incompatible changes, or at the very least detect/telegraph any potential issues as early as possible. We do have a CI job to run downstream package tests on latest dev Bokeh branch. To date these have been on python packages, but we could look into how we might support a Julia API generator test. Alternatively, if there is something that would help you test dev Bokeh versions on this repo's CI, please let us know how we can help

Lastly, I'd say that we would be delighted to mention and link this projects in the upcoming 3.0 release blog post, or tweet about them from the Bokeh twitter account, etc. Please let us know is that would be OK cc @tcmetzger @pavithraes

**Comment by poldavezac** [comment]
@bryevdv Thanks for your message. I'd be happy to have this package mentioned in the blog post or the tweets.

Looking at release 3.0, it seems some work will be required to update the serialization since it have quite a few breaking changes.
I intend to work on this in the coming month.

As for adding Julia to your own CI, that's probably a lot of work for your team if there's only one project using it. I think I can probably come up with something on my side which will be good enough for this package.
